/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.wrapper.core.jni;

public final class StoredObjectType {
  public final static int STORED_OBJ_STRING = otapiJNI.STORED_OBJ_STRING_get();
  public final static int STORED_OBJ_STRING_MAP = otapiJNI.STORED_OBJ_STRING_MAP_get();
  public final static int STORED_OBJ_WALLET_DATA = otapiJNI.STORED_OBJ_WALLET_DATA_get();
  public final static int STORED_OBJ_BITCOIN_ACCT = otapiJNI.STORED_OBJ_BITCOIN_ACCT_get();
  public final static int STORED_OBJ_BITCOIN_SERVER = otapiJNI.STORED_OBJ_BITCOIN_SERVER_get();
  public final static int STORED_OBJ_SERVER_INFO = otapiJNI.STORED_OBJ_SERVER_INFO_get();
  public final static int STORED_OBJ_CONTACT_NYM = otapiJNI.STORED_OBJ_CONTACT_NYM_get();
  public final static int STORED_OBJ_CONTACT_ACCT = otapiJNI.STORED_OBJ_CONTACT_ACCT_get();
  public final static int STORED_OBJ_CONTACT = otapiJNI.STORED_OBJ_CONTACT_get();
  public final static int STORED_OBJ_ADDRESS_BOOK = otapiJNI.STORED_OBJ_ADDRESS_BOOK_get();
  public final static int STORED_OBJ_ERROR = otapiJNI.STORED_OBJ_ERROR_get();
}

