/************************************************************
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

 *                 M O N E Y C H A N G E R
 *
 *  Open Transactions:
 *       Financial Cryptography and Digital Cash
 *       Library, Protocol, API, Server, and GUI 
 *    
 *    	 -- Anonymous Numbered Accounts.
 *    	 -- Untraceable Digital Cash.
 *    	 -- Triple-Signed Receipts.
 *    	 -- Cheques, Vouchers, Transfers, Inboxes.
 *    	 -- Basket Currencies, Markets, Payment Plans.
 *    	 -- Signed, XML, Ricardian-style Contracts.
 *    
 *  Copyright (C) 2010-2012 by "Fellow Traveler" (A pseudonym)
 *
 *  EMAIL:
 *  FellowTraveler@rayservers.net
 *  
 *  FINGERPRINT:
 *  9DD5 90EB 9292 4B48 0484  7910 0308 00ED F951 BB8E
 *
 *  BITCOIN:  1NtTPVVjDsUfDWybS4BwvHpG2pdS9RnYyQ
 *
 *  OFFICIAL PROJECT WIKI:
 *  https://github.com/FellowTraveler/Moneychanger
 *  https://github.com/FellowTraveler/Open-Transactions/wiki
 *
 *  WEBSITE:
 *  http://www.OpenTransactions.org/
 *    
 *  Components and licensing:
 *   -- Moneychanger..A Java client GUI.....LICENSE:.....GPLv3
 *   -- OTLib.........A class library.......LICENSE:...LAGPLv3 
 *   -- OT-API........A client API..........LICENSE:...LAGPLv3
 *   -- testwallet....Command-line client...LICENSE:...LAGPLv3
 *   -- OT-Server.....Server Application....LICENSE:....AGPLv3
 *  Github.com/FellowTraveler/Open-Transactions/wiki/Components
 *
 *  All of the above OT components were designed and written by
 *  Fellow Traveler, with the exception of Moneychanger, which
 *  was contracted out to Vicky C (livewire_3001@yahoo.com).
 *
 *  -----------------------------------------------------
 *
 *   LICENSE:
 *   This program is free software: you can redistribute it
 *   and/or modify it under the terms of the GNU General
 *   Public License as published by the Free Software
 *   Foundation, either version 3 of the License, or (at your
 *   option) any later version.
 *
 *   You should have received a copy of the GNU General
 *   Public License along with this program.  If not, see:
 *   http://www.gnu.org/licenses/
 *
 *   If you would like to use this software outside of the free
 *   software license, please contact FellowTraveler.
 *   (Unfortunately many will run anonymously and untraceably,
 *   so who could really stop them?)
 *   
 *   DISCLAIMER:
 *   This program is distributed in the hope that it will be
 *   useful, but WITHOUT ANY WARRANTY; without even the implied
 *   warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 *   PURPOSE.  See the GNU General Public License for more
 *   details.
 
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.11 (Darwin)

iQIcBAEBCAAGBQJOj7gfAAoJEAMIAO35UbuOs3sP/2rrjSdYu/AsXcgLK9/9CP4a
lIJfw3KLvybKZjZW5r5j+4xUlCYIqPZSI66PGDChGPMPFcZQN6M4Ddpn9kbctymS
sdTXvbdFhpbV6k2wSa1Fz97ygfXJc/7MDTmHYbZ53hVV8AoUBrCHWtVttkQD31o3
Pn/qGmy+jOgTvjEXhjEpV66pDkMWze1SiI1MArHUziCYoxItuM45x0EfzwQIqlo3
ku2R7rRTtqm47Dgea12psWrjbPS5XRL1Q8Hs38Z1J0JdFlfn6cJYe52Iiluzof6M
kCLhy6FH8QfIADfrKkFP48EIhnVquDlkV9AlJ1r217K3cpK2jEjlZUnGBECMAMEo
pSXXk1BLNgxsa4yaXCgHY92/MhgtcdCMLkcCq6MWUTGZsLGiWIiQGmO9mwBfNIlY
SawlIviuS5DiE/D16A290Byxhha/5e144cIiKm27fSQra8eogUXNfZdZeuv6n69v
t8QjeBjoLhe5/KnRNoGLpSXhPphsWLRSJBru77ZU2msHfmkNfcP2UoEUCfNTfTbE
XpyRfeyRVowVKeKunV9KUSHgdD5wa6RUeyodAbaHvWrFpIpNkaFIP9OwhRULpjx0
arwVNYucbX1qb2I8HBm2u+IRWQTONp74TFFjU0/CVAXu2DeJKY5mL4zDej35c5j9
AK+ZirdWhhoHeWR1tAkN
=RcXP
-----END PGP SIGNATURE-----
 **************************************************************/

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OpenTransactionAccountTopPanel.java
 *
 * Created on 18 Mar, 2011, 7:40:38 AM
 */
package com.moneychanger.ui.panels;

import com.moneychanger.core.OpenTransactionAccount;
import com.moneychanger.core.dataobjects.OTDetails;
import com.moneychanger.ui.dialogs.DepositCashDialog;
import com.moneychanger.ui.dialogs.DepositChequeDialog;
import com.moneychanger.ui.dialogs.ExchangeBasketDialog;
import com.moneychanger.ui.dialogs.OTWriteCheque;
import com.moneychanger.ui.dialogs.SendTransferDialog;
import com.moneychanger.ui.dialogs.WithdrawCashDialog;
import com.moneychanger.ui.dialogs.WithdrawVoucherDialog;
import com.moneychanger.core.util.Utility;
import java.awt.Cursor;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Vicky C
 */
public class OpenTransactionAccountTopPanel extends javax.swing.JPanel {

    /** Creates new form OpenTransactionAccountTopPanel */
    public OpenTransactionAccountTopPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel_AssetTypeName = new javax.swing.JLabel();
        jTextField_AssetName = new javax.swing.JTextField();
        jLabel_CurrentBalance = new javax.swing.JLabel();
        jTextField_Balance = new javax.swing.JTextField();
        jButton_DownloadAccountFiles = new javax.swing.JButton();
        jButton_VerifyFiles = new javax.swing.JButton();
        jLabel_AssetID = new javax.swing.JLabel();
        jTextField_AssetID = new javax.swing.JTextField();
        jLabel_NymName = new javax.swing.JLabel();
        jTextField_NymName = new javax.swing.JTextField();
        jLabel_NymID = new javax.swing.JLabel();
        jTextField_NymID = new javax.swing.JTextField();
        jLabel_AccountName = new javax.swing.JLabel();
        jTextField_AccountName = new javax.swing.JTextField();
        jLabel_AccountID = new javax.swing.JLabel();
        jTextField_AccountID = new javax.swing.JTextField();
        jLabel_ServerName = new javax.swing.JLabel();
        jTextField_ServerName = new javax.swing.JTextField();
        jLabel_ServerID = new javax.swing.JLabel();
        jTextField_ServerID = new javax.swing.JTextField();
        jPanel_AccountActions = new javax.swing.JPanel();
        jButton_WriteCheque = new javax.swing.JButton();
        jButton_DepositCheque = new javax.swing.JButton();
        jButton_WithdrawCash = new javax.swing.JButton();
        jButton_DepositCash = new javax.swing.JButton();
        jButton_SendTransfer = new javax.swing.JButton();
        jButton_PurchaseVoucher = new javax.swing.JButton();
        jPanel_AccountBasket = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel_BasketName = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 390));
        setLayout(new java.awt.GridBagLayout());

        jLabel_AssetTypeName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(OpenTransactionAccountTopPanel.class);
        jLabel_AssetTypeName.setText(resourceMap.getString("jLabel_AssetTypeName.text")); // NOI18N
        jLabel_AssetTypeName.setMinimumSize(new java.awt.Dimension(80, 24));
        jLabel_AssetTypeName.setName("jLabel_AssetTypeName"); // NOI18N
        jLabel_AssetTypeName.setPreferredSize(new java.awt.Dimension(100, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(jLabel_AssetTypeName, gridBagConstraints);

        jTextField_AssetName.setBackground(resourceMap.getColor("jTextField_AssetName.background")); // NOI18N
        jTextField_AssetName.setEditable(false);
        jTextField_AssetName.setName("jTextField_AssetName"); // NOI18N
        jTextField_AssetName.setPreferredSize(new java.awt.Dimension(6, 24));
        jTextField_AssetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AssetNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(jTextField_AssetName, gridBagConstraints);

        jLabel_CurrentBalance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_CurrentBalance.setText(resourceMap.getString("jLabel_CurrentBalance.text")); // NOI18N
        jLabel_CurrentBalance.setMinimumSize(new java.awt.Dimension(80, 24));
        jLabel_CurrentBalance.setName("jLabel_CurrentBalance"); // NOI18N
        jLabel_CurrentBalance.setPreferredSize(new java.awt.Dimension(100, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(jLabel_CurrentBalance, gridBagConstraints);

        jTextField_Balance.setEditable(false);
        jTextField_Balance.setName("jTextField_Balance"); // NOI18N
        jTextField_Balance.setPreferredSize(new java.awt.Dimension(6, 24));
        jTextField_Balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_BalanceActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(jTextField_Balance, gridBagConstraints);

        jButton_DownloadAccountFiles.setText(resourceMap.getString("jButton_DownloadAccountFiles.text")); // NOI18N
        jButton_DownloadAccountFiles.setMinimumSize(new java.awt.Dimension(140, 25));
        jButton_DownloadAccountFiles.setName("jButton_DownloadAccountFiles"); // NOI18N
        jButton_DownloadAccountFiles.setPreferredSize(new java.awt.Dimension(220, 25));
        jButton_DownloadAccountFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DownloadAccountFilesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 40);
        add(jButton_DownloadAccountFiles, gridBagConstraints);

        jButton_VerifyFiles.setText(resourceMap.getString("jButton_VerifyFiles.text")); // NOI18N
        jButton_VerifyFiles.setMaximumSize(null);
        jButton_VerifyFiles.setMinimumSize(new java.awt.Dimension(140, 25));
        jButton_VerifyFiles.setName("jButton_VerifyFiles"); // NOI18N
        jButton_VerifyFiles.setPreferredSize(new java.awt.Dimension(220, 25));
        jButton_VerifyFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VerifyFilesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 40);
        add(jButton_VerifyFiles, gridBagConstraints);

        jLabel_AssetID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_AssetID.setText(resourceMap.getString("jLabel_AssetID.text")); // NOI18N
        jLabel_AssetID.setMinimumSize(new java.awt.Dimension(80, 24));
        jLabel_AssetID.setName("jLabel_AssetID"); // NOI18N
        jLabel_AssetID.setPreferredSize(new java.awt.Dimension(100, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(jLabel_AssetID, gridBagConstraints);

        jTextField_AssetID.setEditable(false);
        jTextField_AssetID.setName("jTextField_AssetID"); // NOI18N
        jTextField_AssetID.setPreferredSize(new java.awt.Dimension(6, 24));
        jTextField_AssetID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AssetIDActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 20);
        add(jTextField_AssetID, gridBagConstraints);

        jLabel_NymName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_NymName.setText(resourceMap.getString("jLabel_NymName.text")); // NOI18N
        jLabel_NymName.setMinimumSize(new java.awt.Dimension(80, 24));
        jLabel_NymName.setName("jLabel_NymName"); // NOI18N
        jLabel_NymName.setPreferredSize(new java.awt.Dimension(100, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(4, 10, 4, 4);
        add(jLabel_NymName, gridBagConstraints);

        jTextField_NymName.setText(resourceMap.getString("jTextField_NymName.text")); // NOI18N
        jTextField_NymName.setName("jTextField_NymName"); // NOI18N
        jTextField_NymName.setPreferredSize(new java.awt.Dimension(6, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(jTextField_NymName, gridBagConstraints);

        jLabel_NymID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_NymID.setText(resourceMap.getString("jLabel_NymID.text")); // NOI18N
        jLabel_NymID.setMinimumSize(new java.awt.Dimension(80, 24));
        jLabel_NymID.setName("jLabel_NymID"); // NOI18N
        jLabel_NymID.setPreferredSize(new java.awt.Dimension(100, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(jLabel_NymID, gridBagConstraints);

        jTextField_NymID.setEditable(false);
        jTextField_NymID.setName("jTextField_NymID"); // NOI18N
        jTextField_NymID.setPreferredSize(new java.awt.Dimension(6, 24));
        jTextField_NymID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NymIDActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 20);
        add(jTextField_NymID, gridBagConstraints);

        jLabel_AccountName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_AccountName.setText(resourceMap.getString("jLabel_AccountName.text")); // NOI18N
        jLabel_AccountName.setMinimumSize(new java.awt.Dimension(80, 24));
        jLabel_AccountName.setName("jLabel_AccountName"); // NOI18N
        jLabel_AccountName.setPreferredSize(new java.awt.Dimension(100, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(4, 10, 4, 4);
        add(jLabel_AccountName, gridBagConstraints);

        jTextField_AccountName.setBackground(resourceMap.getColor("jTextField_AccountName.background")); // NOI18N
        jTextField_AccountName.setEditable(false);
        jTextField_AccountName.setName("jTextField_AccountName"); // NOI18N
        jTextField_AccountName.setPreferredSize(new java.awt.Dimension(6, 24));
        jTextField_AccountName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AccountNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(jTextField_AccountName, gridBagConstraints);

        jLabel_AccountID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_AccountID.setText(resourceMap.getString("jLabel_AccountID.text")); // NOI18N
        jLabel_AccountID.setMinimumSize(new java.awt.Dimension(80, 24));
        jLabel_AccountID.setName("jLabel_AccountID"); // NOI18N
        jLabel_AccountID.setPreferredSize(new java.awt.Dimension(100, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(jLabel_AccountID, gridBagConstraints);

        jTextField_AccountID.setEditable(false);
        jTextField_AccountID.setName("jTextField_AccountID"); // NOI18N
        jTextField_AccountID.setPreferredSize(new java.awt.Dimension(6, 24));
        jTextField_AccountID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AccountIDActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 20);
        add(jTextField_AccountID, gridBagConstraints);

        jLabel_ServerName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_ServerName.setText(resourceMap.getString("jLabel_ServerName.text")); // NOI18N
        jLabel_ServerName.setMinimumSize(new java.awt.Dimension(80, 24));
        jLabel_ServerName.setName("jLabel_ServerName"); // NOI18N
        jLabel_ServerName.setPreferredSize(new java.awt.Dimension(100, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(4, 10, 4, 4);
        add(jLabel_ServerName, gridBagConstraints);

        jTextField_ServerName.setBackground(resourceMap.getColor("jTextField_ServerName.background")); // NOI18N
        jTextField_ServerName.setEditable(false);
        jTextField_ServerName.setName("jTextField_ServerName"); // NOI18N
        jTextField_ServerName.setPreferredSize(new java.awt.Dimension(6, 24));
        jTextField_ServerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ServerNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(jTextField_ServerName, gridBagConstraints);

        jLabel_ServerID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_ServerID.setText(resourceMap.getString("jLabel_ServerID.text")); // NOI18N
        jLabel_ServerID.setMinimumSize(new java.awt.Dimension(80, 24));
        jLabel_ServerID.setName("jLabel_ServerID"); // NOI18N
        jLabel_ServerID.setPreferredSize(new java.awt.Dimension(100, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(jLabel_ServerID, gridBagConstraints);

        jTextField_ServerID.setEditable(false);
        jTextField_ServerID.setName("jTextField_ServerID"); // NOI18N
        jTextField_ServerID.setPreferredSize(new java.awt.Dimension(6, 24));
        jTextField_ServerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ServerIDActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 20);
        add(jTextField_ServerID, gridBagConstraints);

        jPanel_AccountActions.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel_AccountActions.setName("jPanel_AccountActions"); // NOI18N
        jPanel_AccountActions.setLayout(new java.awt.GridBagLayout());

        jButton_WriteCheque.setText(resourceMap.getString("jButton_WriteCheque.text")); // NOI18N
        jButton_WriteCheque.setMinimumSize(new java.awt.Dimension(120, 24));
        jButton_WriteCheque.setName("jButton_WriteCheque"); // NOI18N
        jButton_WriteCheque.setPreferredSize(new java.awt.Dimension(160, 24));
        jButton_WriteCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_WriteChequeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel_AccountActions.add(jButton_WriteCheque, gridBagConstraints);

        jButton_DepositCheque.setText(resourceMap.getString("jButton_DepositCheque.text")); // NOI18N
        jButton_DepositCheque.setMinimumSize(new java.awt.Dimension(120, 24));
        jButton_DepositCheque.setName("jButton_DepositCheque"); // NOI18N
        jButton_DepositCheque.setPreferredSize(new java.awt.Dimension(160, 24));
        jButton_DepositCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DepositChequeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel_AccountActions.add(jButton_DepositCheque, gridBagConstraints);

        jButton_WithdrawCash.setText(resourceMap.getString("jButton_WithdrawCash.text")); // NOI18N
        jButton_WithdrawCash.setMinimumSize(new java.awt.Dimension(120, 24));
        jButton_WithdrawCash.setName("jButton_WithdrawCash"); // NOI18N
        jButton_WithdrawCash.setPreferredSize(new java.awt.Dimension(160, 24));
        jButton_WithdrawCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_WithdrawCashActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel_AccountActions.add(jButton_WithdrawCash, gridBagConstraints);

        jButton_DepositCash.setText(resourceMap.getString("jButton_DepositCash.text")); // NOI18N
        jButton_DepositCash.setMinimumSize(new java.awt.Dimension(120, 24));
        jButton_DepositCash.setName("jButton_DepositCash"); // NOI18N
        jButton_DepositCash.setPreferredSize(new java.awt.Dimension(160, 24));
        jButton_DepositCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DepositCashActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel_AccountActions.add(jButton_DepositCash, gridBagConstraints);

        jButton_SendTransfer.setText(resourceMap.getString("jButton_SendTransfer.text")); // NOI18N
        jButton_SendTransfer.setMinimumSize(new java.awt.Dimension(120, 24));
        jButton_SendTransfer.setName("jButton_SendTransfer"); // NOI18N
        jButton_SendTransfer.setPreferredSize(new java.awt.Dimension(160, 24));
        jButton_SendTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SendTransferActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel_AccountActions.add(jButton_SendTransfer, gridBagConstraints);

        jButton_PurchaseVoucher.setText(resourceMap.getString("jButton_PurchaseVoucher.text")); // NOI18N
        jButton_PurchaseVoucher.setMinimumSize(new java.awt.Dimension(120, 24));
        jButton_PurchaseVoucher.setName("jButton_PurchaseVoucher"); // NOI18N
        jButton_PurchaseVoucher.setPreferredSize(new java.awt.Dimension(160, 24));
        jButton_PurchaseVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PurchaseVoucherActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel_AccountActions.add(jButton_PurchaseVoucher, gridBagConstraints);

        jPanel_AccountBasket.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel_AccountBasket.border.title"))); // NOI18N
        jPanel_AccountBasket.setMinimumSize(new java.awt.Dimension(180, 80));
        jPanel_AccountBasket.setName("jPanel_AccountBasket"); // NOI18N
        jPanel_AccountBasket.setPreferredSize(new java.awt.Dimension(220, 80));
        jPanel_AccountBasket.setVisible(false);

        jButton9.setText(resourceMap.getString("jButton9.text")); // NOI18N
        jButton9.setName("jButton9"); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText(resourceMap.getString("jButton10.text")); // NOI18N
        jButton10.setName("jButton10"); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel_BasketName.setText(resourceMap.getString("jLabel_BasketName.text")); // NOI18N
        jLabel_BasketName.setName("jLabel_BasketName"); // NOI18N

        javax.swing.GroupLayout jPanel_AccountBasketLayout = new javax.swing.GroupLayout(jPanel_AccountBasket);
        jPanel_AccountBasket.setLayout(jPanel_AccountBasketLayout);
        jPanel_AccountBasketLayout.setHorizontalGroup(
            jPanel_AccountBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AccountBasketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_BasketName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_AccountBasketLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(460, 460, 460))
        );
        jPanel_AccountBasketLayout.setVerticalGroup(
            jPanel_AccountBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AccountBasketLayout.createSequentialGroup()
                .addGroup(jPanel_AccountBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_BasketName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_AccountBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = 2;
        jPanel_AccountActions.add(jPanel_AccountBasket, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.weighty = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(jPanel_AccountActions, gridBagConstraints);

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_BalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_BalanceActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField_BalanceActionPerformed

    private void jTextField_AccountNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AccountNameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField_AccountNameActionPerformed

    private void jTextField_ServerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ServerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ServerNameActionPerformed

    private void jTextField_AssetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AssetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AssetNameActionPerformed

    private void jTextField_AccountIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AccountIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AccountIDActionPerformed

    private void jTextField_AssetIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AssetIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AssetIDActionPerformed

    private void jTextField_ServerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ServerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ServerIDActionPerformed

    private void jTextField_NymIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NymIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NymIDActionPerformed

    private void jButton_DepositChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DepositChequeActionPerformed
        new DepositChequeDialog(null, true, jTextField_ServerID.getText(), jTextField_NymID.getText(), jTextField_AccountID.getText()).setVisible(true);
    }//GEN-LAST:event_jButton_DepositChequeActionPerformed

    private void jButton_WithdrawCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_WithdrawCashActionPerformed
        new WithdrawCashDialog(null, true, jTextField_ServerID.getText(), jTextField_NymID.getText(), jTextField_AccountID.getText()).setVisible(true);
    }//GEN-LAST:event_jButton_WithdrawCashActionPerformed

    private void jButton_DepositCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DepositCashActionPerformed
        String[] purseDetails = new OpenTransactionAccount().getPurseBalance(jTextField_ServerID.getText(), jTextField_AssetID.getText(), jTextField_NymID.getText());
        /*if(purseDetails==null){
        JOptionPane.showMessageDialog(this, "Error in cash deposit. Empty purse","Error",JOptionPane.ERROR_MESSAGE);
        return;
        }*/
        new DepositCashDialog(null, true, purseDetails, jTextField_ServerID.getText(), jTextField_NymID.getText(), jTextField_AccountID.getText()).setVisible(true);
    }//GEN-LAST:event_jButton_DepositCashActionPerformed

    private void jButton_PurchaseVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PurchaseVoucherActionPerformed
        new WithdrawVoucherDialog(null, true, jTextField_ServerID.getText(), jTextField_NymID.getText(), jTextField_AccountID.getText()).setVisible(true);
    }//GEN-LAST:event_jButton_PurchaseVoucherActionPerformed

    private void jButton_WriteChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_WriteChequeActionPerformed
        new OTWriteCheque(null, true, jTextField_ServerID.getText(), jTextField_NymID.getText(), jTextField_AccountID.getText(),"").setVisible(true);
    }//GEN-LAST:event_jButton_WriteChequeActionPerformed

    private void jButton_SendTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SendTransferActionPerformed
        new SendTransferDialog(null, true, jTextField_ServerID.getText(), jTextField_NymID.getText(), jTextField_AccountID.getText()).setVisible(true);
    }//GEN-LAST:event_jButton_SendTransferActionPerformed

    private void jButton_DownloadAccountFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DownloadAccountFilesActionPerformed
        String accountID = jTextField_AccountID.getText();
        try {
            OpenTransactionAccount openTransaction = new OpenTransactionAccount();
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            boolean isSuccess = Utility.getInboxOutboxAccount(accountID, true); // download the data.
            if (isSuccess) {
                JOptionPane.showMessageDialog(this, "Files downloaded successfully", "Processing Success", JOptionPane.INFORMATION_MESSAGE);
                OpenTransactionAccountBottomPanel.setOTTables(openTransaction.getInboxData(accountID), openTransaction.getOutboxData(accountID));
            } else {
                JOptionPane.showMessageDialog(this, "Error in downloading latest account files", "Server Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
}//GEN-LAST:event_jButton_DownloadAccountFilesActionPerformed

    private void jButton_VerifyFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VerifyFilesActionPerformed
        OpenTransactionAccount otAccount = new OpenTransactionAccount();
        int isSuccess = otAccount.verifyFiles(jTextField_ServerID.getText(), jTextField_NymID.getText(), jTextField_AccountID.getText());
        if (isSuccess == 0) {
            JOptionPane.showMessageDialog(null, "The intermediary files for this account have all been VERIFIED against the last signed receipt", "Verified", JOptionPane.INFORMATION_MESSAGE);
        } else if (isSuccess == 1) {
            JOptionPane.showMessageDialog(null, "The intermediary files for this account have FAILED to verify against the last signed receipt", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (isSuccess == 2) {
            JOptionPane.showMessageDialog(null, "There is no receipt for this account", "Empty", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton_VerifyFilesActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
            OpenTransactionAccount otAccount = new OpenTransactionAccount();
            String basket = otAccount.showBasket(jTextField_ServerID.getText(), jTextField_NymID.getText(), jTextField_AssetID.getText());
            if (basket != null && basket.length() > 0) {
                new ExchangeBasketDialog(null, true, basket, true, jTextField_ServerID.getText(), jTextField_NymID.getText(), jTextField_AccountID.getText(), jTextField_AssetID.getText()).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Error getting basket curreny list", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (InterruptedException ex) {
            Logger.getLogger(OpenTransactionAccountTopPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            OpenTransactionAccount otAccount = new OpenTransactionAccount();
            String basket = otAccount.showBasket(jTextField_ServerID.getText(), jTextField_NymID.getText(), jTextField_AssetID.getText());
            if (basket != null && basket.length() > 0) {
                new ExchangeBasketDialog(null, true, basket, false, jTextField_ServerID.getText(), jTextField_NymID.getText(), jTextField_AccountID.getText(), jTextField_AssetID.getText()).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Error getting basket curreny list", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (InterruptedException ex) {
            Logger.getLogger(OpenTransactionAccountTopPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton_DepositCash;
    private javax.swing.JButton jButton_DepositCheque;
    private javax.swing.JButton jButton_DownloadAccountFiles;
    private javax.swing.JButton jButton_PurchaseVoucher;
    private javax.swing.JButton jButton_SendTransfer;
    private javax.swing.JButton jButton_VerifyFiles;
    private javax.swing.JButton jButton_WithdrawCash;
    private javax.swing.JButton jButton_WriteCheque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_AccountID;
    private javax.swing.JLabel jLabel_AccountName;
    private javax.swing.JLabel jLabel_AssetID;
    private javax.swing.JLabel jLabel_AssetTypeName;
    private static javax.swing.JLabel jLabel_BasketName;
    private javax.swing.JLabel jLabel_CurrentBalance;
    private javax.swing.JLabel jLabel_NymID;
    private javax.swing.JLabel jLabel_NymName;
    private javax.swing.JLabel jLabel_ServerID;
    private javax.swing.JLabel jLabel_ServerName;
    private javax.swing.JPanel jPanel_AccountActions;
    private static javax.swing.JPanel jPanel_AccountBasket;
    private static javax.swing.JTextField jTextField_AccountID;
    private static javax.swing.JTextField jTextField_AccountName;
    private static javax.swing.JTextField jTextField_AssetID;
    private static javax.swing.JTextField jTextField_AssetName;
    private static javax.swing.JTextField jTextField_Balance;
    private static javax.swing.JTextField jTextField_NymID;
    private static javax.swing.JTextField jTextField_NymName;
    private static javax.swing.JTextField jTextField_ServerID;
    private static javax.swing.JTextField jTextField_ServerName;
    // End of variables declaration//GEN-END:variables

    public static void populateOTDetails(OTDetails otDetails) {

        jTextField_Balance.setText(otDetails.getBalance());
        jTextField_AccountID.setText(otDetails.getAccountID());
        jTextField_AssetID.setText(otDetails.getAssetID());
        jTextField_ServerID.setText(otDetails.getServerID());
        jTextField_NymID.setText(otDetails.getNymID());
        jTextField_AccountName.setText(otDetails.getAccountName());
        jTextField_ServerName.setText(otDetails.getServerName());
        jTextField_AssetName.setText(otDetails.getAssetName());
        jTextField_NymName.setText(otDetails.getNymName());

        if (otDetails.getBasketName() != null) {
            System.out.println("otDetails.getBasketName():"+otDetails.getBasketName());
            jPanel_AccountBasket.setVisible(true);
            jLabel_BasketName.setToolTipText(otDetails.getBasketName());
            jLabel_BasketName.setText(otDetails.getBasketName());
        } else {
            jPanel_AccountBasket.setVisible(false);
        }

        jTextField_Balance.setCaretPosition(0);
        jTextField_AccountID.setCaretPosition(0);
        jTextField_AssetID.setCaretPosition(0);
        jTextField_ServerID.setCaretPosition(0);
        jTextField_NymID.setCaretPosition(0);
        jTextField_AccountName.setCaretPosition(0);
        jTextField_ServerName.setCaretPosition(0);
        jTextField_AssetName.setCaretPosition(0);
        jTextField_NymName.setCaretPosition(0);



    }

    public static void clearPanel() {

        if (jTextField_Balance != null && jTextField_AccountName != null && jTextField_ServerName != null
                && jTextField_AssetName != null && jTextField_NymName != null && jTextField_AccountID != null
                && jTextField_AssetID != null && jTextField_ServerID != null && jTextField_NymID != null) {
            jTextField_Balance.setText("");
            jTextField_AccountName.setText("");
            jTextField_ServerName.setText("");
            jTextField_AssetName.setText("");
            jTextField_NymName.setText("");
            jTextField_AccountID.setText("");
            jTextField_AssetID.setText("");
            jTextField_ServerID.setText("");
            jTextField_NymID.setText("");
        }
    }
}
